- requirements.txt
Having this file checked into the repository means that the ignore line in .gitignore is essentially nonfunctional. This patch removes requirements.txt so that the ignore line in .gitignore is functional and the generated requirements.txt doesn't accidentally end up in any commits.
> Remove requirements.txt file from repository

- .github/workflows/main.yml
- WORKSPACE
As a public repository, Gematria gets unlimited free minutes for running jobs on Github CI. We've had good success using Github actions to ensure code is formatted properly/tests pass in MLGO, so I'm opening up this patch to do the same with Gematria so that it's less likely developers miss something.
Note that I'm using external dependencies here to make the setup easier, which may not be super desirable due to issues like maintenance concerns, but migrating off of them should be trivial. Something to note, however.
> Add formatting jobs to CI

- g3doc/obtaining-training-data.md
This patch adds in documentation on obtaining training data from the BHive dataset, makes some notes about other datasets, and marks out future directions (particularly extraction from ELF binaries). This spells out a couple things in the process that aren't too difficult to figure out but might not be very obvious (such as running all of the tooling through bazel), especially for those unfamiliar with the tooling/build system.
> Add documentation on obtaining training data

- Dockerfile
Recently we moved from declaring an entire transitive closure in requirements.txt (and generating that with Bazel) to declaring just the top-level packages along with version information in requirements.in. This change brought with it a different set of commands for setup which breaks the existing Dockerfile. This patch fixes the Dockerfile to match the new setup.
> Update Dockerfile after dependency installation change

- .gitignore
- CONTRIBUTING
- WORKSPACE
As mentioned in the documentation this is necessary to use tooling like `clangd` in an IDE. I'm not sure what tooling was used internally to develop the project, but this seems to be fairly standard in other open source projects.
> Add tooling to create a compile_commands.json

- BUILD
- gematria/datasets/python/BUILD
- tools/BUILD
- tools/build_pip_package.py
This patch adds in a setup.py file and associated bazel build rules to build python wheels that can be used for distribution on pypi. This is primarily aimed at making it easier to use Gematria tooling in other projects, particularly google/ml-compiler-opt.
This still needs a little bit of work (why it is marked as draft). I plan on making the dependencies on shared objects in the `setup.py` implicit since they're explicitly defined in Bazel and also fix up a couple remaining dependency issues within the bazel build. There are a couple hacky things that I am not a particular fan of such as the symlinking of the `pybind11_abseil/status.so` shared object to get it into a path that `setuptools` will take, but that can't be avoided with base `setuptools`. I still need to investigate if using …
> Add in setup.py to create wheels for distribution

- gematria/datasets/bhive_importer.cc
- gematria/datasets/bhive_importer.h
- gematria/datasets/bhive_importer_test.cc
- gematria/datasets/python/bhive_importer.cc
- gematria/datasets/python/bhive_importer_test.py
- gematria/datasets/python/import_from_bhive.py
Other datasets such as Andreas Abel's uica-eval use slightly different CSV formats and there's no real reason not to support them since the only thing that differs is the column layout. This patch adds in two new flags that allow specifying the columns of the basic block hex and throughput data.
Should be mostly complete, but is in desperate need of formatting (which is why I've marked it as a draft).
> Add support for importing CSVs with differing formats

- gematria/experiments/access_pattern_bm/README.md
Currently the documentation shows setting --pfm=true to get access to performance counters in the access pattern benchmarks, but Google benchmark only recognizes --pfm=1. This patch corrects the documentation for this.
> Update documentation to correct config options for benchmarks

- gematria/llvm/canonicalizer.cc
This patch fixes the C++ formatting which was causing the clang-format job to fail. Very minor change, but if we're going to have C++ formatting in CI, we should probably keep it green.
> Fix C++ Formatting with clang-format

- WORKSPACE
The bazel files were also changed after the recent push and no longer are formatted correctly according to buildifier. This patch does the necessary reformatting.
> Reformat bazel files with buildifier

- .github/workflows/main.yaml
This patch adds support for running the bazel build in CI to easily catch bazel build regressions. Running the bazel tests will be added in a future patch.
> Add support for running bazel build in CI

- gematria/experiments/access_pattern_bm/BUILD
The experimental code depends on x86-64 specific intrinsics, and breaks the build on Apple silicon and other non-x86 platforms.
> Mark the cache/perf counter experiments as x86-64 only.

- .github/workflows/main.yaml
Currently the github actions workflow runs whenever something is pushed to a branch or against any pull request. This means that if a branch is pushed to the main google/gematria repository and a PR is opened against google/gematria:main, there will be duplicate jobs, one for the push event and one for the pull request event. This patch fixes this behavior by restricting the push event to the main branch.
> Only run push CI on main branch

- .github/workflows/main.yaml
For some reason, using an older version of pyink causes odd failures in the CI complaining about missing functions in a vendored dependency. Upgrading to the most recent version fixes the issue. Maybe should try and make this more hermetic at some point with a lockfile or something, but for now this is a simple fix.
> Fix python formatting CI job

- gematria/llvm/asm_parser_test.cc
- gematria/testing/llvm_test.cc
The previous commit reworked all of the llvm includes, but broke the code formatting job in the meantime. This patch fixes the code formatting to get the CI back to green.
> Clang-format some files

- .github/workflows/main.yaml
Currently the Bazel build is failing due to the CI trying to pull in bazel v7.0.0. This patch pins the bazel version to v6.4.0 which gets the CI green again, allowing further time to work on performing the necessary migration steps to get everything working properly with v7.0.0.
> Set Bazel version in CI

- WORKSPACE
- gematria/datasets/BUILD
- gematria/datasets/find_accessed_addrs_exegesis.cc
- gematria/datasets/find_accessed_addrs_exegesis.h
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
- gematria/datasets/find_accessed_addrs_test.cc
This patch adds in an alternative to the existing find_accessed_addrs infrastructure that uses llvm-exegesis as a backend. We believe this will more closely match the execution environment of the benchmarking environment and should avoid some of the pitfalls of the existing memory annotation infrastructure (at the current expense of speed).
> Add exegesis BB annotator

- Dockerfile
Nothing currently wrong with the old bazelisk version, but we're two minor versions out of date at this point and there's no real point in not updating.
> Bump Bazelisk version in container to 1.19.0

- WORKSPACE
- gematria/datasets/find_accessed_addrs_exegesis.cc
This patch bumps the LLVM version to a recent ToT commit and patches the Exegesis annotator so that everything compiles and works correctly.
Mostly wanting to get this in as I remember debugging weird failures due to things compiling despite a constructor changing within upstream Exegesis.
> Bump LLVM version

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
This patch moves `file_counter` out of the global scope to where it is relevant in `main`, as requested in the original review.
> Address PR feedback in convert_bhive_to_llvm_exegesis_input

- llvm_cm/tools/llvm-cm/llvm-cm.cpp
A couple additional cases were recently added into the BB Address Map section in https://github.com/llvm/llvm-project/pull/74128. This broke llvm-cm as a couple method names changed. This patch provides the quick fix to get everything working.
Eventually llvm-cm will need some work to support multiple BBRanges within a single function.
> Fix llvm-cm after switch to BBRanges

- README.md
- llvm_cm/CMakeLists.txt
- llvm_cm/test/X86/bb-frequency.s
- llvm_cm/test/X86/lit.local.cfg
- llvm_cm/test/lit.cfg
- llvm_cm/test/lit.site.cfg.in
This patch sets up a ninja target for testing llvm-cm, akin to the tool specific test targets in the monorepo. This allows for actually running the tests. Documentation has been added to the README.
> Add test target for llvm-cm

- gematria/datasets/find_accessed_addrs_exegesis.cc
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
This patch makes the exegesis annotator work with mappings that are not page aligned. Currently if a segfault occurs at an address that isn't page aligned, Exegesis will try and map an address at that address and then the mmap call will silently fail as there is no error handling wired up for that and it will segfault again, thus creating a loop within the annotator.
> Make exegesis annotator work with mappings that aren't page aligned

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
This patch adjusts the constants in the BHive conversion script from the default values added in with the script to the values used within the original BHive paper. These constants were experimentally determined within the BHive paper to be high enough to not underflow/access addresses in the first page yet low enough to not access any addresses above the virtual address space ceiling. Anecdotally, these constants have also seemed to work better than the original ones. In addition, this patch prefixes the memory value with zeroes so that llvm-exegesis is able to assume the correct bit width.
> Change constants in BHive conversion script

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
This patch fixes the register class that the BHive to Exegesis conversion script uses. Currently it is only pulling in registers that don't have a REX encoding, which doesn't even include R9-R15. This patch fixes that behavior by using the more generic LLVM 64-bit GPR Register class, but specifically looking at registers that don't require a REX2 encoding, as there is no hardware in the wild yet that supports APX.
> Make exegesis conversion script use appropriate register class

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
This patch adds a JSON output option to the BHive converter. This makes it significantly easier to implement other scripts down the line that ingest this data. This also cuts down the number of inodes that a large data set will use by a significant amount, which can be a problem on some file systems.
> Add JSON output option to BHive converter

- .github/workflows/main.yaml
- gematria/datasets/BUILD
- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
- gematria/llvm/llvm_to_absl.h
This patch adds support for using the exegesis annotator in the BHive conversion script.
> Add support for exegesis annotator in BHive conversion script

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
This patch adds a progress reporting flag to the annotator script. This can be quite useful when using a slower implementation of FindAccessedAddrs like FindAccessedAddrsExegesis to get a gauge on what sort of progress is being made and to show that the application isn't stuck somewhere when processing a large number of blocks.
> Add progress reporting flag to annotator script

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
This patch fixes an off-by-one error in the annotator JSON output. Essentially, the very first block would automatically trigger a write to the file since the file count was zero, and zero modulo anything is still zero, which was the condition for writing to a file. This becomes a problem if there are fewer blocks than blocks_per_json_file as after processing all the blocks, the final chunk will be written, but it will overwrite the first chunk in this case, leaving blocks out. This patch fixes that behavior by simpling computing the module with file_counter +1, which has the same effect but avoids this behavior.
> Fix off by one error in annotator JSON output

- gematria/datasets/bhive_importer.cc
- gematria/datasets/bhive_importer.h
- gematria/datasets/bhive_importer_test.cc
This patch adds a new function that refactors out some functionality from the existing proto generation functions to create a proto directly from disassembled instructions. This allows user to do their own disassembly (like for easy access to the llvm MCInsts) and efficiently create a proto afterwards.
> Add function to create proto from disassembled instructions

- .github/workflows/main.yaml
- gematria/datasets/BUILD
This patch enables running the Bazel tests in CI which allows us to automatically catch regressions and more easily ensure that PRs aren't breaking anything/the additional (tested) functionality is working properly. This patch doesn't enable anything using perf_counters to be tested in CI as Github Actions VMs don't have access to performance counters. This effect is achieved by creating a bazel test tag and excluding it on the bazel test invocation.
> Enable Bazel tests in CI

- gematria/datasets/BUILD
- gematria/datasets/tests/blocks_per_json_file.test
- gematria/datasets/tests/flag_errors.test
- gematria/datasets/tests/lit.cfg.py
- gematria/datasets/tests/max_bb_count.test
This patch adds some additional lit regression tests for the Exegesis conversion script to test functionality that was previously implemented/improved now that we actually have testing facilities. This should cover all the recently landed PRs. More regression tests will come with time as bugs get fixed.
> Add additional lit tests for Exegesis conversion script

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
This patch adds a none annotator type to
convert_bhive_to_llvm_exegesis_input that doesn't run any annotator. This is useful for looking at the output assembly for debugging purposes.
> Add none annotator type

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
- gematria/datasets/tests/report_progress.test
Currently, the --report_progress_every flag, even with the default value, will always report progress on the first block. This is not the intended behavior, as no output should be given with the default value. This patch fixes that behavior and also adds a test to ensure that the flag functions as intended in the default value case and in the value-provided case.
Not really super critical to functionality, but a little bit annoying to have this.
> Improve --report_progress_every flag

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
- gematria/datasets/tests/blocks_per_json_file.test
Currently, the logic in convert_bhive_to_llvm_exegesis_input will create extra (empty) files as the output at the end runs unconditionally rather than when there are actually blocks to output. This means that if we have a number of blocks that is an exact multiple of the value in blocks_per_json_file, we end up getting no blocks after the loop, which means we output an empty JSON file.
Fixes #61.
> Make blocks_per_json_file flag not output extra files

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
This patch fixes a clang-formatting issue introduced in a previous patch.
> Fix clang-formatting issue

- gematria/datasets/find_accessed_addrs_exegesis.cc
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
This patch makes the exegesis annotator error out if we try to map the zero address as we are not able to do this with mmap. To solve this while still being able to annotate the blocks, we probably need some way to adjust the register/memory values.
> Error out if we try to annotate a zero address

- gematria/datasets/find_accessed_addrs_exegesis.cc
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
Currently, there is a failure condition seen in some blocks where the annotator finds a segfault, tells exegesis to map a page there, and then the block fails again at the same address. This needs some debugging, but currently it will be helpful if we can just log a warning message and skip this basic block.
> Make exegesis annotator error out when remapping an address

- gematria/experiments/access_pattern_bm/stl_container.h
This probably has been "just working" because we're using a compiler pre D127675. An up to date compiler would require the missing include.
> Exeriments: add missing `#include <iterator>`

- .bazelrc
This patch sets --define=use_fast_cpp_protos=true to ensure that we are using the cpp protos instead of the python protos. This results in about an 85% reduction in time spent loading protos due to the lack of needing to serialize/deserialize at the language interface.
> Switch to using fast cpp protos

- requirements.txt
This is to deal with the depandabot alert and does not seem to hurt anything.
> Bump idna to 3.7

- llvm_cm/test/X86/bb-frequency.s
- llvm_cm/test/X86/multi_func.s
- llvm_cm/test/X86/profile-dump.s
Currently the llvm-cm tests are quite sensitive to small FP differences as they evaluate a model where the results are not guaranteed to be exact across hardware. Check the two most significant figures and then regex that we have numbers to make them invariant against slight changes.
> Make llvm-cm tests invariant against small FP differences

- .github/workflows/main.yaml
- llvm_cm/tools/llvm-cm/llvm-cm.cpp
This patch bumps the clang format version in CI to v18 as v18 is the latest LLVM release (currently) and includes quite a few patches for clang-format.
> Bump clang format version in CI to v18

- .bazelrc
This patch adds sanitizer configs to .bazelrc so a developer can simply use --config=asan or --config=tsan on a specific test to see if there are any issues. It seems like asan might be catching some issues I will have to look into this in a bit.
> Add sanitizer configs to bazel

- gematria/datasets/BUILD.bazel
- gematria/datasets/extract_bbs_from_obj.cc
- gematria/datasets/extract_bbs_from_obj_lib.cc
- gematria/datasets/extract_bbs_from_obj_lib.h
This patch refactors extract_bbs_from_obj into a library that accepts a memory buffer so that Python bindings can be added, making it easier to write a beam pipeine without writing files out to a temporary directory.
> Refactor extract_bbs_from_obj into library

- gematria/datasets/BUILD.bazel
- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
- gematria/datasets/convert_bhive_to_llvm_exegesis_input_tests/blocks_per_json_file.test
- gematria/datasets/convert_bhive_to_llvm_exegesis_input_tests/conversion.test
- gematria/datasets/convert_bhive_to_llvm_exegesis_input_tests/json.test
- gematria/datasets/find_accessed_addrs_exegesis.cc
This patch makes convert_bhive_to_llvm_exegesis_inputs use information from AccessedAddrs like the initial register values and the block contents to emit information to the file rather than assuming a default register value/default block content.
> Use information from AccessedAddrs in conversion tool

- gematria/datasets/python/extract_tokens_file.py
tfrecord.read_protos expects a list of strings rather than an individual string path. Convert the single file into an array to satisfy the type checker.
> Fix type error in extract_tokens_file

- gematria/datasets/extract_bbs_from_obj_lib.cc
The comparator function for sorting basic blocks in extract_bbs_from_obj previously compared the start address of the LHS to the size of the RHS rather than comparing the start addresses. This patch fixes this behavior. This makes the code correct (or at least fixes one correctness issue) and fixes a libc++ assertion (when assertions are enabled).
> Fix sort comparator in extract_bbs_from_obj

- gematria/basic_block/basic_block.cc
- gematria/basic_block/basic_block.h
- gematria/basic_block/basic_block_protos.cc
- gematria/basic_block/basic_block_protos.h
- gematria/basic_block/basic_block_protos_test.cc
- gematria/basic_block/basic_block_test.cc
- gematria/basic_block/python/BUILD.bazel
- gematria/basic_block/python/basic_block.cc
- gematria/basic_block/python/basic_block_protos.cc
- gematria/basic_block/python/basic_block_protos_test.py
- gematria/basic_block/python/basic_block_test.py
- gematria/proto/BUILD.bazel
- gematria/proto/annotation.proto
- gematria/proto/canonicalized_instruction.proto
Adds instruction annotations to the proto specification (`AnnotationProto`) , the graph builder basic block representation (`Annotation`), and functions to convert between the two (`AnnotationFromProto` and `ProtoFromAnnotation`).
> Add instruction annotations to the basic block representations.

- gematria/datasets/python/extract_bbs_from_obj_test.py
- gematria/testing/BUILD.bazel
This patch cleansup some minor mistakes that I left in some previous PRs, particularly not renaming a test away from a default value and leaving an export_files rule in a BUILD file after deleting it.
> Cleanup minor mistakes missed in other PRs

- .github/workflows/main.yaml
This patch adds the current date to the bazel cache so that a new cache will be stored every day rather than whenever the hashed files change. This should significantly improve the build times for bazel as cache hits should increase.
> Add date to bazel cache

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
According to the twine documentation, twine assignment when using concatenation can lead to undefined behavior. This was leading to test failures for convert_bhive_to_llvm_exegesis_input when running tests with -c opt. This patch fixes this behavior by converting the twine to a string and storing it in a std::string rather than trying to store it as a twine.
Fixes #147.
> Fix twine-related UB in convert_bhive_to_llvm_exegesis_input

- gematria/granite/graph_builder_model_inference.cc
- gematria/granite/graph_builder_model_inference.h
* Remove the need to know tensor indices at compile time by examining the tensor names used in the tflite models.
> Add name-based lookups to the tflite inference API.

- Dockerfile
As of 2024-07-23, `bazel build ...` fails unless `lld` is explicitly installed via `apt-get install`.
> Add an explicit dependency on `lld` to `Dockerfile`.

- gematria/granite/graph_builder_model_inference.cc
Currently GetInputTensorName can potentially return from a non-void function without actually returning anything. Add `__builtin_unreachable` to the end of the function to mark that we expect this case to never happen.
> Add __builtin_unreachable to end of GetInputTensorName

- gematria/granite/python/token_graph_builder_model.py
Other installations of tensorflow/tf_keras can have complicated `__init__.py`s that pytype isn't able to comprehend correctly. Disable pytype around the one case of this so we can utilize gematria with alternative dependency installations.
> Disable pytype module-attr around glorot_normal

- .github/workflows/main.yaml
- WORKSPACE
* The LLVM version used by the CMake CI is now pinned to that specified by `WORKSPACE`.
* It must be manually bumped alongside the one in `WORKSPACE`.
> Pin LLVM version used by CMake CI.

- llvm_cm/test/X86/multi_func.s
- llvm_cm/test/X86/profile-dump.s
Bumping to a recent LLVM version causes the LLVM tests to fail. This patch updates the tests and makes them slightly more resilient against small changes.
> Fix llvm-cm tests against recent LLVM

- .clangd
This patch adds the MissingIncludes option to the clangd config so that IWYU violations are warned about in the IDE, assuming it uses clangd as the LSP.
> Add MissingIncludes to clangd config

- gematria/datasets/BUILD.bazel
- gematria/datasets/process_and_filter_bbs.cc
- gematria/datasets/process_and_filter_bbs_lib.cc
- gematria/datasets/process_and_filter_bbs_lib.h
This will enable the addition of unittests to verify the functionality of the script along with the addition of python bindings so that this tooling can be easily used from within a beam pipeline.
> Refactor process_and_filter_bbs into a library

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
- gematria/datasets/find_accessed_addrs.cc
- gematria/datasets/find_accessed_addrs.h
- gematria/datasets/find_accessed_addrs_exegesis.cc
- gematria/datasets/find_accessed_addrs_exegesis.h
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
- gematria/datasets/find_accessed_addrs_test.cc
Now that we are having the find_accessed_addrs scripts add data like initial register values, memory values, and more, just calling the struct they procued AccessedAddrs makes less sense. This patch changes the name to BlockAnnotations to better capture what is stored within the struct.
> Renamed AccessedAddrs BlockAnnotations

- gematria/datasets/basic_block_utils.cc
- gematria/datasets/basic_block_utils.h
- gematria/datasets/basic_block_utils_test.cc
- gematria/datasets/bhive_importer.cc
- gematria/datasets/bhive_importer.h
- gematria/datasets/bhive_importer_test.cc
- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
- gematria/datasets/exegesis_benchmark.cc
- gematria/datasets/extract_bbs_from_obj.cc
- gematria/datasets/extract_bbs_from_obj_lib.cc
- gematria/datasets/find_accessed_addrs.cc
- gematria/datasets/find_accessed_addrs.h
- gematria/datasets/find_accessed_addrs_exegesis.cc
- gematria/datasets/find_accessed_addrs_exegesis.h
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
- gematria/datasets/find_accessed_addrs_test.cc
- gematria/datasets/process_and_filter_bbs.cc
- gematria/datasets/process_and_filter_bbs_lib.cc
- gematria/datasets/python/bhive_importer.cc
- gematria/datasets/python/extract_bbs_from_obj.cc
This patch fixes IWYU warnings under the dataset directory by using clangd to update all the headers within the C++/C files.
> Fix IWYU warnings in Datasets

- .github/workflows/main.yaml
This patch bumps several Github Actions deps to newer versions. This is intended to get rid of deprecation warnings related to old NodeJS versions.
> Bump Github Actions Deps

- gematria/datasets/BUILD.bazel
- gematria/datasets/python/BUILD.bazel
- gematria/datasets/python/bhive_to_exegesis.cc
- gematria/datasets/python/bhive_to_exegesis_test.py
This patch adds python bindings for the bhive_to_exegesis library. This enables us to get annotated basic blocks from raw hex values. Future patches will refactor exegesis_benchmark into a library and add additional functions that will take in the AnnotatedBlock class so that we can then get throughput information.
> Add python bindings for bhive_to_exegesis

- gematria/datasets/BUILD.bazel
- gematria/datasets/exegesis_benchmark.cc
- gematria/datasets/exegesis_benchmark_lib.cc
- gematria/datasets/exegesis_benchmark_lib.h
This patch refactors the majority of the functionality in the exegesis_benchmark binary into a library. This allows reuse in other parts of the code base, particularly beam pipelines once python bindings have been written.
> Refactor exegesis_benchmark functionality into a library

- gematria/datasets/BUILD.bazel
- gematria/datasets/exegesis_benchmark.cc
- gematria/datasets/exegesis_benchmark_lib.cc
- gematria/datasets/exegesis_benchmark_lib.h
- gematria/datasets/exegesis_benchmark_lib_test.cc
This patch adds functionality in exegesis_benchmark_lib to directly create a benchmark configuration (BenchmarkCode) from annotations (BlockAnnotations). This is intended to be used primarily from the python bindings, where we get annotations directly from the annotator and then need to run benchmarking directly on that rather than serializing to JSON.
> Add support for creating a benchmark configuration from annotations

- gematria/datasets/exegesis_benchmark_lib.cc
There is a compiler warning marked as -Werror inside google3 that fires on this code due to Gematria using uintptr_t but llvm-exegesis using intptr_t. For now, static cast this so that we can do an import.
> Add intptr_t static cast to silence compiler warning

- gematria/datasets/pipelines/compile_modules_lib.py
Originally, the optimization pass list in OptimizeModules was typed as a Sequence[Sequence[str]], with the intention being that each individual pass would be a separate string. This doesn't make sense with how opt takes in pass pipelines, which was why the typing information was incorrect by the time the code landed. This patch changes the typing information to be correct and renames the variables to hopefully provide more clarity.
> Fix types and rename variables for clarity

- gematria/datasets/pipelines/compile_modules_lib.py
This patch adds a docstring for get_bbs. This function is long enough that having a docstring is probably useful. The internal linting tools also complain about a lack of a docstring.
> Add docstring for get_bbs

- gematria/datasets/pipelines/BUILD.bazel
- gematria/datasets/pipelines/compile_modules_lib.py
- gematria/datasets/pipelines/compile_modules_lib_test.py
This patch adds an additional step for filtering and processing basic blocks to the compilation pipeline. This gets us one step closer to fully annotating blocks and then saving them before another benchmarking pipeline takes over.
> Add filtering and processing BBs to the compilation pipeline

- gematria/datasets/pipelines/compile_modules.py
This patch adds a remove memory accessing instructions flag to the compile_modules binary. This is necessary now that the get_bbs function requires this parameter.
> Add remove memory accessing instructions flag to compile_modules binary

- Dockerfile
This patch adds the packages libelf-dev and m4 to the docker image. These are needed to successfully build annotating_importer and run annotating_importer_test.
> Add libelf and m4 to the docker image

- gematria/datasets/annotating_importer.h
- gematria/datasets/annotating_importer_test.cc
- gematria/datasets/bhive_importer.h
This patch does some minor cleanup in gematria/datasets such as removing unused includes, adding includes where necessary to be IWYU compliant, and adding docstrings where necessary.
This based off of feedback from the 9-4-24 import.
> Minor cleanup in datasets

- gematria/llvm/asm_parser.cc
- gematria/llvm/asm_parser_test.cc
- gematria/llvm/canonicalizer.cc
- gematria/llvm/canonicalizer_test.cc
- gematria/llvm/diagnostics_test.cc
- gematria/llvm/disassembler_test.cc
- gematria/llvm/llvm_architecture_support_test.cc
- gematria/llvm/python/llvm_architecture_support.cc
This patch cleans up extra/missing includes in gematria/llvm to make it IWYU compliant (at least according to clangd). Some other misc cleanup like deleting dead functions was also performed.
> Cleanup includes in gematria/llvm

- gematria/datasets/pipelines/benchmark_bbs_lib.py
This patch fixes capitalization of tuple in benchmark_bbs_lib. In a patch update, we switched from Tuple to tuple (import from typing to the standard python builtin), but I forgot to update one of the types, which causes build failures locally.
The build failures did not occur in CI due to the test requiring perf counters to pass.
> Fix tuple capitalization in benchmark_bbs_lib

- .github/workflows/main.yaml
- WORKSPACE
This patch bumps LLVM to ToT (at least when I copied the commit SHA from Github). This is necessary for some cleanup releated to register index lookups within Exegesis as a recent patch has moved that around which makes things much cleaner for us.
> Bump LLVM to ToT

- .github/workflows/main.yaml
- WORKSPACE
- gematria/datasets/exegesis_benchmark_lib.cc
This patch replaces our direct search of the register name to number mapping to a function now included in LLVMState that handles that for us, leaving us to solely deal with the error handling. Necessary now that the accessor for the register name to number mapping will be deleted soonish.
> Use LLVMState helper for getting register index

- gematria/utils/BUILD.bazel
> Enable layering_checks for gematria/utils

- gematria/testing/BUILD.bazel
- gematria/testing/python/BUILD.bazel
- gematria/testing/testdata/BUILD.bazel
> Enable layering_checks for gematria/testing

- gematria/datasets/BUILD.bazel
- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
- gematria/datasets/convert_bhive_to_llvm_exegesis_input_tests/BUILD.bazel
- gematria/datasets/extract_bbs_from_obj_tests/BUILD.bazel
- gematria/datasets/pipelines/BUILD.bazel
- gematria/datasets/python/BUILD.bazel
> Enable layering checks for gematria/datasets

- gematria/sequence/BUILD.bazel
- gematria/sequence/python/BUILD.bazel
> Enable layering checks for gematria/sequence

- gematria/proto/BUILD.bazel
> Enable layering checks for gematria/proto

- gematria/model/BUILD.bazel
- gematria/model/python/BUILD.bazel
> Enable layering checks for gematria/model

- gematria/llvm/BUILD.bazel
- gematria/llvm/python/BUILD.bazel
> Enable layering checks for gematria/llvm

- gematria/io/BUILD.bazel
- gematria/io/python/BUILD.bazel
> Enable layering checks for gematria/io

- gematria/granite/BUILD.bazel
- gematria/granite/python/BUILD.bazel
> Enable layering checks for gematria/granite

- gematria/experiments/BUILD.bazel
- gematria/experiments/access_pattern_bm/BUILD.bazel
> Enable layering checks for gematria/experiments

- gematria/basic_block/BUILD.bazel
- gematria/basic_block/python/BUILD.bazel
> Enable layering checks for gematria/basic_block

- Dockerfile
This patch updates clang/lld within the docker image to LLVM 19. This is necessary for the use of the -fbasic-block-address-map flag, which we need to switch a couple of tests over to as the old option, -fbasic-block-sections=labels is deprecated.
> Bump LLVM in docker image to LLVM 19

- .github/workflows/main.yaml
- WORKSPACE
- gematria/datasets/exegesis_benchmark_lib.cc
- gematria/datasets/find_accessed_addrs_exegesis.cc
This includes a new patch for exegesis that enables pinning the benchmarking process to a specific core.
> Bump LLVM version to near ToT

- gematria/datasets/block_wrapper.S
- gematria/datasets/block_wrapper.h
- gematria/datasets/find_accessed_addrs.cc
- gematria/datasets/find_accessed_addrs.h
* Rename "before_block" and "after_block" to "prologue" and "epilogue"
* Use a typedef for the function type rather than stating it in the cast
* Fix a typo
> Minor cleanups for find_accessed_addrs

- WORKSPACE
This patch bumps the pybind11 protobuf version. This enables us to take advantage of an upstreamed patch instead of using a custom fork.
> Bump pybind11 protobuf version

- gematria/datasets/python/BUILD.bazel
- gematria/datasets/python/annotating_importer.cc
- gematria/datasets/python/annotating_importer_test.py
- gematria/datasets/python/import_annotated_basic_blocks.py
- gematria/testing/python/basic_blocks_with_throughput.py
* Add bindings to the driver function.
* Add a small python script that exposes the binding for use.
> Add Python bindings to `annotating_importer`.

- gematria/datasets/pipelines/compile_modules_lib.py
This patch adds metrics for the module compilation/annotation pipeline. These will show up in the Beam executor dashboard (i.e., GCP Dataflow, Spark, Flink, etc.) and provide valuable insight about what is actually happening, as currently a lot of the information is lost.
> Add metrics for module compilation pipeline

- gematria/datasets/pipelines/benchmark_bbs_lib.py
This patch adds metrics to the benchmarking pipeline, which will be reported by the beam executor to give more insight into what happened during the execution.
> Add metrics to benchmarking pipeline

- gematria/datasets/python/BUILD.bazel
- gematria/datasets/python/annotating_importer_test.py
A while back, the canonical way within Gematria to get bazel runfiles was switched to using the runfiles library installed through pypi. This patch makes annotating_importer_test use this as it seems like this was written before the change and did not get updated afterwards.
> Switch runfiles usage to python library

- gematria/datasets/find_accessed_addrs_test.cc
This patch replaces use of cpuid in inline assembly with calls to __builtin_cpu_supports. This makes the code significantly simpler and also means that all of the footguns involved with cpuid are handled by the abstraction rather than manually.
> Replace cpuid usage with __builtin_cpu_supports

- gematria/llvm/python/BUILD.bazel
This patch cleans up one final use of rules_python where we do not actually need it. We cannot remove the entire dependency as it includes the bazel rules that we need in order to build the python elements of the project.
> Cleanup extra uses of rules_python

- gematria/testing/python/basic_blocks_with_throughput.py
unittest.TestCase has no documented assertLen function. Change this to `absltest.TestCase` as the subclass so that the type-checker is happy even though this class is exclusively a mix-in.
> Change unittest.TestCase to absl TestCase

- gematria/testing/python/BUILD.bazel
- gematria/testing/python/basic_blocks_with_throughput.py
- gematria/testing/python/basic_blocks_with_throughput_test.py
- gematria/testing/testdata/annotated_basic_blocks_with_throughput.pbtxt
* Fixes incorrect logic for loading of annotated basic blocks for testing in `basic_blocks_with_throughput.py`.
* Previously, we would silently load un-annotated blocks.
> Fix loading of annotated blocks for tests.

- gematria/datasets/convert_bhive_to_llvm_exegesis_input.cc
- gematria/datasets/convert_bhive_to_llvm_exegesis_input_tests/loop_register.test
- gematria/datasets/exegesis_benchmark_lib.cc
- gematria/datasets/exegesis_benchmark_lib_test.cc
This patch makes it so that JSON files produced by convert_bhive_to_llvm_exegesis_input use names for the loop registers rather than simply emitting register numbers. This involved modifying the loop register test to actually check that we were emitting loop register names (which we were already doing) and updating the parsing code in exegesis_benchmark_lib to parse loop register names rather than expecting register indices that might change from one LLVM version to the next.
> Use loop register name in annotated bb JSON

- gematria/datasets/BUILD.bazel
- gematria/datasets/annotating_importer_test.cc
This patch fixes annotating_importer_test so that it can be run internally as the bazel runfiles rule only kind of exists. We instead just get the value from the TEST_SRCDIR environment variable and then append the object file/perf data file path to it to get the data that we need.
> Enable running annotations importer test internally

- gematria/datasets/pipelines/compile_modules_lib.py
- gematria/datasets/pipelines/compile_modules_lib_test.py
This patch moves the code getting the LLVM binary paths to the beam DoFn setup function rather than __init__. This is necessary as some implementations of get_llvm_binary_path require extracting the binary from an archive to a temporary directory on the local machine. Putting this in __init__ does not guarantee that this happens on anything other than the machine running it (one) whereas running it in setup ensures the appropriate setup takes place for each worker instance.
> Get LLVM Binary paths in setup instead of init

- gematria/datasets/annotating_importer.h
Simple cleanup for readability.
> [Readability] Remove `const` from declarations in `annotating_importer`.

- gematria/datasets/BUILD.bazel
- gematria/datasets/annotating_importer.cc
- gematria/datasets/annotating_importer.h
* Minor refactoring of usages of `ELF64LEObjectFile`s to `ELFObjectFileBase`s in `annotating_importer`.
* This change is meant to help merge some functionality in `annotating_importer` with `extract_bbs_from_obj_lib`.
> Minimize use of `ELF64LEObjectFile` over `ELFObjectFileBase` in `annotating_importer`.

- gematria/datasets/bhive_to_exegesis.cc
- gematria/datasets/bhive_to_exegesis.h
- gematria/datasets/pipelines/BUILD.bazel
- gematria/datasets/pipelines/compile_modules.py
- gematria/datasets/pipelines/compile_modules_lib_test.py
This patch fixes a user after move in BHiveToExegesis/related classes where we would create a LLVMState, pass it into a couple other constructors to create things that would store a reference to LLVMState, and then promptly move it to call the BHiveToExegesis constructor. This resulted in use after moves, which were ultimately caught by ubsan. This patch fixes that behavior by encapsulating LLVMState within a unique_ptr to prevent the problems.
The exegesis annotator is also enabled in the compile_modules invocation script and test coverage is added now that it works.
> Fix use after move to get exegesis annotator working in pipeline

- gematria/datasets/bhive_to_exegesis.cc
- gematria/datasets/bhive_to_exegesis.h
This patch passes unique_ptrs within bhive_to_exegesis by value rather than by r-value reference.
Suggested in #249.
> Pass unique_ptr by value in bhive_to_exegesis

- gematria/datasets/pipelines/compile_modules.py
This prevents us from having to maintain the array in two places.
> Use a single dictionary for annotator mappings

- gematria/datasets/basic_block_utils.cc
- gematria/datasets/basic_block_utils_test.cc
Certain instructions implicitly use the df register, which means we need to support it for the exegesis annotator so that we do not get MC verification errors. Additionally, it is good to explicitly define the state to ensure we have deterministic execution. This patch adds support for the df register by explicitly returning eflags as the super register as LLVM does not seem to explicitly model df as a subregister of eflags.
Part of a fix for #251.
> Add support for df register in basic_block_utils

- gematria/datasets/pipelines/benchmark_bbs_lib.py
This patch adds a counter to track the number of blocks that have succeeded. This is quite a useful metric to look at on the status page for the Beam executor to track how fast things are progressing and how far along things are.
Also actually increment the failed blocks counter because apparently I forgot to do that in the last patch.
> Add benchmark success blocks counter to benchmarking pipeline

- gematria/datasets/find_accessed_addrs_exegesis.cc
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
We currently abort if we have an unhandled register, which includes the AVX512BW registers before this patch. This patch changes the SSE/AVX2 register classes to the AVX512 register versions so we pick up the registers as expected.
> Make exegesis annotator support AVX512BW registers

- WORKSPACE
This brings in some patches that allow for explicitly setting the df register on X86.
> Bump LLVM version to 842fd1537521d38913aec5c9a081afedf97d88fe

- WORKSPACE
- gematria/datasets/basic_block_utils.cc
- gematria/datasets/basic_block_utils_test.cc
- gematria/datasets/find_accessed_addrs_exegesis.cc
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
Now that llvm-exegesis has support for explicitly setting the df register, we should explicitly define df rather than eflags/rflags when something in the block uses df. This fixes a MC verification error when using the loop snippet repetitor due to implicitly defined registers not being set as live-ins.
> Explicitly define df register

- gematria/datasets/annotating_importer.cc
- gematria/datasets/annotating_importer.h
* There is no longer any point of keeping `owning_binary_` as part of the `AnnotatingImporter` state, since it is not re-used between calls to `GetAnnotatedBasicBlockProtos`, which is the intended use of `AnnotatingImporter`.
* This change is meant to help merge some functionality from `annotating_importer` with `extract_bbs_from_obj_lib`.
> Remove `owning_binary_` from `AnnotatingImporter` state.

- gematria/datasets/find_accessed_addrs_exegesis_test.cc
vmovdqu does not work with the 128-bit/256-bit AVX512 registers. Switch the instruction so that the test actually works on system with AVX512VL support. This was causing test failures on system with AVX512. I did not catch this originally as I was testing on znver2.
> Fix incorrect instruction mnemonic in exegesis annotator test

- gematria/datasets/exegesis_benchmark_lib.h
This patch updates the comment on getRegisterFromName in exegesis_benchmark_lib.h to get rid of the TODO as that was addressed in \#209. Also add some additional context about why the function exists.
> Update comment in exegesis_benchmark_lib.h

- WORKSPACE
This patch bumps the LLVM verson to include some fixes related to CPU
pinning of the benchmarking subprocess.
> Bump LLVM Version to cd66c9b6a04689659348c0a3ff4c1205b1133fe9

- gematria/datasets/exegesis_benchmark_lib.h
- gematria/datasets/find_accessed_addrs_exegesis_test.cc
- gematria/datasets/pipelines/benchmark_cpu_scheduler.py
- gematria/datasets/pipelines/benchmark_cpu_scheduler_test.py
This patch introduces the BenchmarkScheduler interface that sets the CPU
affinity mask for the current process and gets a benchmark core for use
by llvm-exegesis. This patch additional introduces a BenchmarkScheduler
implementation that simply does nothing, which will preserve the
behavior that we have currently where we do not explicitly set CPU
masks.
> Add basic benchmark scheduler

- .github/workflows/main.yaml
This patch bumps the LLVM commit used by the CI system for the CMake build. This should be kept in sync with what is used for the bazel build, which is something I have forgotten to do for the past couple LLVM commit bumps.
> Bump the CMake LLVM CI commit

- gematria/datasets/pipelines/benchmark_cpu_scheduler.py
- gematria/datasets/pipelines/benchmark_cpu_scheduler_test.py
This reverts commit 86a1c06721bb216c99b0a895db3ed14fa1e41068.
I apparently accidentally fixed up #271 into #270. This reverts the
changes that accidentally made there way into the tree.
> Revert default benchmark scheduler changes.

- .github/workflows/main.yaml
- gematria/basic_block/basic_block.h
- gematria/datasets/exegesis_benchmark_lib_test.cc
- gematria/datasets/process_and_filter_bbs_lib_test.cc
This patch bumps the clang-format that we are using to v19 to fix some issues that came up in #288.
> Bump clang-format version to v19

- gematria/datasets/annotating_importer.cc
- gematria/datasets/annotating_importer.h
* Pass pointers to the perf profile proto and the main memory mapping instead of storing them as class members.
* The `PerfParser` also does not need to be held on to - it is used only once.
* The `PerfReader` must be held on to since it owns all of the perf related data.
> Remove unnecessary `perf` information from `AnnotatingImporter` state.

- gematria/datasets/annotating_importer.cc
- gematria/datasets/annotating_importer.h
- gematria/datasets/python/import_annotated_basic_blocks.py
* Add a binary name check while identifying the main mapping.
* A new check of the sample PID against the main mapping PID.
* Remove the check for whether the block's code was within the bounds
of the executable segment in terms of file addresses, this is
redundant as long as the mapping is valid.
> Add extra checks to select the right mapping and filter samples within it.

- gematria/datasets/annotating_importer.cc
- gematria/datasets/annotating_importer.h
- gematria/datasets/annotating_importer_test.cc
- gematria/datasets/python/annotating_importer_test.py
- gematria/datasets/python/import_annotated_basic_blocks.py
* Previously, the annotating importer would break in certain
situations, for example if the virtual address the executable segment
is to be loaded at was not page-aligned.
> Fix annotating importer address resolution.

- gematria/datasets/annotating_importer.cc
There is a line in annotating importer that attempts to get the base name of a path from a StringRef. Before this patch, a StringRef was referenced, .str() was called on it, and then it was passed into a function to extract the base name that took in a StringRef and returned a StringRef. Calling .str() caused a temporary string to get created. Given that string is a temporary, it can get deallocated after calling the function to get the basename, resulting in a use after free when the StringRef is referenced later. This patch simply removes the .str() call so that we purely operate with StringRefs to proper backing memory, which fixes the issue.
This fixes the Gematria->Google3 import. Not entirely sure how/why this did not fail in the open.
> Fix use after free in annotating importer

- .github/workflows/main.yaml
- WORKSPACE
This integrates commit 980d66caae62de9b56422a2fdce3f535c2ab325f which
contains an llvm-exegesis patch for perf counter related issues that we
need to handle in Gematria.
> Bump LLVM version to ToT

- gematria/datasets/find_accessed_addrs_exegesis_test.cc
One of the tests in find_accessed_addrs_exegesis_test checks that if we try and annotate the same address multiple times we bail out. It does this by relying on the fact that exegesis does not error out on mmap failures and by trying to annotate a snippet accessing memory above the user space virtual memory ceiling. This is ceiling is higher on newer platforms with five level page tables, so adjust it to be higher than the new ceiling.
https://docs.kernel.org/5.10/x86/x86_64/mm.html
> Fix flaky annotation test

- gematria/llvm/BUILD.bazel
- gematria/llvm/llvm_architecture_support.cc
The overload of createTargetMachine that accepts a string version of the triple is deprecated. Switch over to the version that accepts a llvm::Triple directly to avoid using deprecated functionality.
> Fix deprecated use of createTargetMachine

- gematria/granite/python/BUILD.bazel
This patch shards graph_builder_model_base_test to make testing changes locally a bit quicker latency wise at some slight increased cost in overall compute needed for testing.
> Shard graph_builder_model_base_test

- gematria/granite/python/BUILD.bazel
- gematria/granite/python/run_granite_model.py
The only thing that we needed to keep was the usage of
tf.compat.v1.io.tf_record_iterator that should get removed eventually
when we move over to the actual dataset APIs.
> Remove tf.compat.v1 imports in io/

- gematria/granite/python/gnn_model_base.py
- gematria/granite/python/graph_builder_model_base.py
- gematria/model/python/model_base.py
This patch contains some misc fixes most related to type checking that enable us to import gematria into google after the TF2 migration. Most are pretty standard. We disable an attribute error on run_continuous_evaluation mostly to silence it for now as tf_slim is not really compatible with TF2 and needs to be rewritten.
> Misc fixes for google import

- gematria/model/python/main_function.py
- gematria/model/python/model_base.py
* Logs most of the previously logged scalars.
* Bonus: wraps training in `timer.scoped`.
> Restore TensorBoard summary logging after TF 2 migration.

- gematria/model/python/main_function.py
- gematria/model/python/main_function_test.py
- gematria/model/python/model_base.py
Adds some flags allowing the training loop to be run under the TensorFlow profiler. The profiler is part of the TF 2.x API but should (and appears to) work with TF 1.x models in this way.
> Add TensorFlow profiler to training loop.

- gematria/granite/python/gnn_model_base.py
This patch provides a custom implementation of trainable_variables in
gnn_model_base. Theoretically this should have been made unnecessary by
\#337, but the interanl version of Tensorflow refuses to recurse into
the modules inside of the GraphNetworkLayer classes. This patch fixes
that by just returning the values regardless.
> Override gnn_model_base trainable_variables

- .github/workflows/main.yaml
- WORKSPACE
This includes https://github.com/llvm/llvm-project/pull/137581 which makes it a bit nicer to deal with verification failures, some of which come from inline assembly and would be difficult to fix within LLVM.
> Bump LLVM to 88c4ef2f9fc0cda90c8452bc1c46844aaa722a3e

- .github/workflows/main.yaml
* The CI for #346 fails because the runner runs out of disk space.
* CI runners should have a disk with plenty of free capacity mounted on `/mnt`.
* This PR moves the Bazel output base there, which should keep us from running into this issue again.
> [CI] Move the Bazel output base to a free disk.

- gematria/model/python/loss_utils.py
Streamlines the computation of the loss and brings it more in line with an eager
TF2 style. 
As a side effect, I've added some duplication of work in repeated normalization of
the outputs. This could be avoided by unwrapping some of the computation, but it's
probably not worth the extra code and complexity. And, at least in theory, the
duplicate ops should be removed by the JIT graph optimizer.
This is a follow-up to ##343.
> Simplified the parameterized loss computation.

- .github/workflows/main.yaml
* The cache action still complains about some permissions after being given write access to output base.
* This gives the runner user ownership of the output base to stop this.
> [CI] Replace `chmod` with `chown` in CI Bazel output base setup.

- gematria/model/python/loss_utils.py
- gematria/model/python/model_base.py
- gematria/model/python/training.py
* The main `tf.function` (`_compute_and_apply_gradients`) was forcing re-traces on every call for some model configurations with a significant performance penalty. Passing `reduce_retracing=True` seems to be enough to prevent this: TF is able to construct a `ConcreteFunction` with the right input signature after seeing a few invocations.
* Marks model functions using `match-case` as excluded from AutoGraph conversion. AutoGraph fails to convert them anyways, and this suppresses related warnings.
* Makes `TrainingEpochStats` print correctly as actual values, rather than the enclosing Tensors.
> Prevent `tf.function` retracing and minor TF2 fixes.

- .github/workflows/main.yaml
- BUILD.bazel
This test takes a while and times out on quite a few systems (including CI and my sandy bridge desktop). Bump the timeout by adding a timeout option to the rule which passes extra keyword arguments to the underlying test rule.
> Bump timeout for requirements test

- .github/workflows/main.yaml
- WORKSPACE
- gematria/llvm/llvm_architecture_support.cc
This patch bumps LLVM to a7091951f0bbdeb78a76f933394a7754c5990371 and fixes an ambiguous cast that was already fixed internally.
This patch also switches to using the http_archive integrity argument instead of the sha argument for validating the LLVM archive given that is what bazel 7 seems to spit out by default.
> Bump LLVM to a7091951f0bbdeb78a76f933394a7754c5990371

- Dockerfile
This patch bumps the bazelisk version in the Dockerfile. No particular reason, but it has not been updated in a while and the newer version works so we might as well bump it.
> Bump bazelisk version in Dockerfile

- gematria/granite/python/gnn_model_base.py
- gematria/model/python/training.py
There are a couple new pytype issues introduced by recent commits. This patch fixes them. Namely the percentiles is expected to be a list of lists rather than just a list and _unwrap_if_tensor does not currently report returning that. We can also have None edge/node/global output sizes in GraphNetworkLayer, so make sure to support that as well.
> Misc pytype fixes for import

- gematria/model/python/training.py
pytype is not smart enough to realize that we will only have tf.Tensor objects if we successfully pass the tf.is_tensor call. So just disable the attribute error to keep pytype happy.
Forgot to include this in the last commit.
> Disable attribute error in _unwrap_if_tensor

- gematria/granite/graph_builder.cc
* This fixes a bug in `StrAppendList`, causing commas separating items in the returned list string representation to be missing.
> Fix bug in `StrAppendList` for `BasicBlockGraphBuilder::DebugString`.

- .github/workflows/main.yaml
- WORKSPACE
- gematria/llvm/asm_parser.cc
This patch bumps LLVM to 0df365180 and fixes one section asm_parser.cc
to work with the new LLVM version.
> Bump LLVM to 0df365180
